/**
 * export.ts — Product Route Bundle Exporter
 *
 * 为无循环 Agent 环境输出完整 Prompt Bundle。
 *
 * 用法:
 *   npx tsx src/export.ts --lang zh-CN                单语 + 示例（完整包）
 *   npx tsx src/export.ts --lang zh-CN --no-examples   单语，不含示例（纯规则包）
 *   npx tsx src/export.ts --lang zh-CN --examples-only 仅示例
 *   npx tsx src/export.ts --multi                      多语 + 示例
 *   npx tsx src/export.ts --multi --no-examples        多语，不含示例
 *   npx tsx src/export.ts                              默认：所有可用单语 + 示例
 *
 * 输出:
 *   dist/product-route.zh-CN.bundle.md       单语
 *   dist/product-route.en.bundle.md          单语
 *   dist/product-route.multi.bundle.md       多语
 *   dist/product-route.examples.zh-CN.md     仅示例
 */

import * as fs from "fs";
import * as path from "path";

// ── 配置 ──────────────────────────────────────────────

const PROJECT_ROOT = path.resolve(__dirname, "..");
const SCHEMA_VERSION = "0.1.0";
const SKILL_VERSION = "0.1.0";

interface BundleConfig {
  lang: string;
  label: string;
  skillDir: string;
  outputFile: string;
}

const BUNDLES: BundleConfig[] = [
  {
    lang: "zh-CN",
    label: "中文运行包",
    skillDir: "skills/product-route.zh-CN",
    outputFile: "dist/product-route.zh-CN.bundle.md",
  },
  {
    lang: "en",
    label: "English Runtime",
    skillDir: "skills/product-route.en",
    outputFile: "dist/product-route.en.bundle.md",
  },
];

const MULTI_OUTPUT = "dist/product-route.multi.bundle.md";

const REF_FILES = [
  "scoring-rules.md",
  "routing-rules.md",
  "evidence-rules.md",
  "risk-gates.md",
  "report-template.md",
];

// ── 工具函数 ──────────────────────────────────────────

function readFileIfExists(filePath: string): string | null {
  try {
    return fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}

function ensureDir(filePath: string): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

// ── 单语 Bundle 构建 ─────────────────────────────────

function buildSingleBundle(config: BundleConfig, includeExamples: boolean): string | null {
  const skillDir = path.resolve(PROJECT_ROOT, config.skillDir);

  const skillMd = readFileIfExists(path.join(skillDir, "SKILL.md"));
  if (!skillMd) {
    console.log(`[SKIP] ${config.lang}: SKILL.md not found`);
    return null;
  }

  const referencesDir = path.join(skillDir, "references");
  const parts: string[] = [];

  // 1. SKILL.md
  parts.push(skillMd);
  parts.push("");

  // 2. References
  parts.push("---");
  parts.push("");
  parts.push("## Bundled References");
  parts.push("");

  for (const refFile of REF_FILES) {
    const content = readFileIfExists(path.join(referencesDir, refFile));
    if (content) {
      parts.push(`### ${refFile}`);
      parts.push("");
      parts.push(content);
      parts.push("");
    } else {
      console.warn(`[WARN] ${config.lang}: missing reference: ${refFile}`);
    }
  }

  // 3. Examples (optional)
  if (includeExamples) {
    const examplesDir = path.join(skillDir, "examples");
    const examplesFiles = fs.existsSync(examplesDir) ? fs.readdirSync(examplesDir).filter(f => f.endsWith(".md")) : [];
    if (examplesFiles.length > 0) {
      parts.push("---");
      parts.push("");
      parts.push("## Bundled Examples");
      parts.push("");
      parts.push("### 使用规则");
      parts.push("");
      parts.push("以下示例用于展示 Product Route 的输出格式和路由判断方式。");
      parts.push("");
      parts.push("**重要约束：**");
      parts.push("");
      parts.push("1. 示例中的证据仅用于示范，不得在新的产品评估中直接复用为当前证据。");
      parts.push("2. 评估新产品想法时必须重新建立 Evidence Table。");
      parts.push("3. 如果运行环境没有联网、MCP 或 Provider，不得把示例中的竞品、价格、社区讨论当作已验证事实。");
      parts.push("4. 示例整体 confidence 最高为 B（示例证据无真实可追溯来源链接）。");
      parts.push("5. 实际评估时，如果有 A 级可追溯证据，confidence 可以达到 A。");
      parts.push("");

      for (const exampleFile of examplesFiles) {
        const content = readFileIfExists(path.join(examplesDir, exampleFile));
        if (content) {
          parts.push(`### ${exampleFile}`);
          parts.push("");
          parts.push(content);
          parts.push("");
        }
      }
    }
  }

  // 4. Footer
  const modeTag = includeExamples ? "full" : "rules-only";
  parts.push("---");
  parts.push("");
  parts.push(
    `> Generated by export.ts | Language: ${config.lang} | Mode: ${modeTag} | Schema: ${SCHEMA_VERSION} | Skill: ${SKILL_VERSION}`
  );
  parts.push("");

  return parts.join("\n");
}

// ── 多语结构构建 ─────────────────────────────────────

function buildMultiBundle(configs: BundleConfig[], includeExamples: boolean): string {
  const parts: string[] = [];
  const available = configs.filter(
    (c) => readFileIfExists(path.resolve(PROJECT_ROOT, c.skillDir, "SKILL.md")) !== null
  );

  const modeTag = includeExamples ? "full" : "rules-only";

  // ── Header ──
  parts.push("# Product Route · Multi-Language Bundle");
  parts.push("");
  parts.push("> 为无循环 Agent 环境提供的完整多语 Prompt 结构。");
  parts.push("> Agent 应根据 `runtime_language` 选择对应语言区块加载。");
  parts.push("");
  parts.push(`> Generated: ${new Date().toISOString().split("T")[0]}`);
  parts.push(`> Schema version: ${SCHEMA_VERSION}`);
  parts.push(`> Skill version: ${SKILL_VERSION}`);
  parts.push(`> Mode: ${modeTag}`);
  parts.push(`> Available languages: ${available.map((c) => c.lang).join(", ")}`);
  parts.push("");

  // ── Language Index ──
  parts.push("## Language Index");
  parts.push("");
  parts.push("| Language | Label | Source Directory |");
  parts.push("|---|---|---|");
  for (const c of available) {
    parts.push(`| ${c.lang} | ${c.label} | ${c.skillDir}/ |`);
  }
  parts.push("");

  // ── Usage Instructions ──
  parts.push("## Usage");
  parts.push("");
  parts.push("**Single-language Agent:** Select the block matching your `runtime_language`.");
  parts.push("Only load ONE language block. Do not mix rules from different languages in the same session.");
  parts.push("");
  parts.push("**Multi-language Router:** If your agent routes by detected language,");
  parts.push("load the appropriate block based on the user's language preference.");
  parts.push("");
  parts.push("---");
  parts.push("");

  // ── Language Blocks ──
  for (const config of available) {
    const content = buildSingleBundle(config, includeExamples);
    if (!content) continue;

    parts.push(`# ── ${config.lang} · ${config.label} ──`);
    parts.push("");
    parts.push(
      `> **Runtime language: ${config.lang}** — Only load this block if the session language is ${config.lang}.`
    );
    parts.push("> Do NOT load this block together with other language blocks.");
    parts.push("");
    parts.push(content);
    parts.push("");
    parts.push("---");
    parts.push("");
  }

  // ── Footer ──
  parts.push("## End of Multi-Language Bundle");
  parts.push("");
  parts.push(
    `> Generated by export.ts | Mode: multi ${modeTag} | Schema: ${SCHEMA_VERSION} | Skill: ${SKILL_VERSION}`
  );
  parts.push("");

  return parts.join("\n");
}

// ── 仅示例 Bundle ─────────────────────────────────────

function buildExamplesOnlyBundle(config: BundleConfig): string | null {
  const skillDir = path.resolve(PROJECT_ROOT, config.skillDir);
  const examplesDir = path.join(skillDir, "examples");

  if (!fs.existsSync(examplesDir)) {
    console.log(`[SKIP] ${config.lang}: no examples directory`);
    return null;
  }

  const examplesFiles = fs.readdirSync(examplesDir).filter(f => f.endsWith(".md"));
  if (examplesFiles.length === 0) {
    console.log(`[SKIP] ${config.lang}: no example files found`);
    return null;
  }

  const parts: string[] = [];
  parts.push(`# Product Route · Examples · ${config.lang}`);
  parts.push("");
  parts.push("> 仅包含示例评估，不含规则和模板。");
  parts.push("> 用于快速浏览路由判断案例，或作为 Agent 的 few-shot 示例集。");
  parts.push("");
  parts.push(`> Language: ${config.lang} | Skill version: ${SKILL_VERSION}`);
  parts.push(`> Example count: ${examplesFiles.length}`);
  parts.push("");

  for (const exampleFile of examplesFiles) {
    const content = readFileIfExists(path.join(examplesDir, exampleFile));
    if (content) {
      parts.push("---");
      parts.push("");
      parts.push(`## ${exampleFile}`);
      parts.push("");
      parts.push(content);
      parts.push("");
    }
  }

  parts.push("---");
  parts.push("");
  parts.push(`> Generated by export.ts | Mode: examples-only | Language: ${config.lang} | Skill: ${SKILL_VERSION}`);
  parts.push("");

  return parts.join("\n");
}

// ── 写入文件 ──────────────────────────────────────────

function writeOutput(filePath: string, content: string): void {
  const fullPath = path.resolve(PROJECT_ROOT, filePath);
  ensureDir(fullPath);
  fs.writeFileSync(fullPath, content, "utf-8");
  console.log(`[OK] Written: ${filePath} (${content.length} chars)`);
}

// ── CLI ───────────────────────────────────────────────

interface ParsedArgs {
  includeExamples: boolean;
  examplesOnly: boolean;
  mode: "single" | "multi" | "all";
  lang?: string;
}

function parseArgs(): ParsedArgs {
  const args = process.argv.slice(2);
  const examplesOnly = args.includes("--examples-only");
  const includeExamples = examplesOnly ? false : !args.includes("--no-examples");

  if (args.includes("--multi")) {
    return { mode: "multi", includeExamples, examplesOnly };
  }

  const langIdx = args.indexOf("--lang");
  if (langIdx !== -1 && args[langIdx + 1]) {
    return { mode: "single", lang: args[langIdx + 1], includeExamples, examplesOnly };
  }

  return { mode: "all", includeExamples, examplesOnly };
}

// ── Main ──────────────────────────────────────────────

function main(): void {
  const parsed = parseArgs();

  const exampleTag = parsed.examplesOnly ? "examples-only" : (parsed.includeExamples ? "included" : "excluded");
  console.log("Product Route Bundle Exporter");
  console.log("==============================");
  console.log(`Mode: ${parsed.mode} | Examples: ${exampleTag}`);
  console.log("");

  switch (parsed.mode) {
    case "single": {
      const config = BUNDLES.find((b) => b.lang === parsed.lang);
      if (!config) {
        console.error(`[ERROR] Unknown language: ${parsed.lang}`);
        console.error(`Available: ${BUNDLES.map((b) => b.lang).join(", ")}`);
        process.exit(1);
      }

      if (parsed.examplesOnly) {
        const content = buildExamplesOnlyBundle(config);
        if (!content) {
          console.error(`[ERROR] No examples found for ${parsed.lang}`);
          process.exit(1);
        }
        const outFile = `dist/product-route.examples.${parsed.lang}.md`;
        writeOutput(outFile, content);
      } else {
        const content = buildSingleBundle(config, parsed.includeExamples);
        if (!content) {
          console.error(`[ERROR] Cannot build bundle for ${parsed.lang}: SKILL.md missing`);
          process.exit(1);
        }
        writeOutput(config.outputFile, content);
      }
      break;
    }

    case "multi": {
      if (parsed.examplesOnly) {
        console.log("[SKIP] --examples-only does not support --multi mode.");
        console.log("Use --lang <lang> --examples-only for a specific language.");
        process.exit(1);
      }
      const content = buildMultiBundle(BUNDLES, parsed.includeExamples);
      writeOutput(MULTI_OUTPUT, content);
      break;
    }

    case "all": {
      if (parsed.examplesOnly) {
        console.log("[SKIP] --examples-only does not support default (all) mode.");
        console.log("Use --lang <lang> --examples-only for a specific language.");
        process.exit(1);
      }
      let built = 0;
      for (const config of BUNDLES) {
        const content = buildSingleBundle(config, parsed.includeExamples);
        if (content) {
          writeOutput(config.outputFile, content);
          built++;
        }
      }
      console.log("");
      console.log(`Done. ${built}/${BUNDLES.length} bundles built.`);
      break;
    }
  }
}

main();
